version: "3"
services:
  mysql:
    image: mariadb:10.5.10
    container_name: aodata-mysql
    restart: on-failure
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_PWD}
    ports:
      - 3306:3306
    volumes:
      - ./mysqldata:/var/lib/mysql
      - ./mysqlbackup:/mysqlbackup
    networks:
      - albiondata
  web:
    image: ruby:3
    build:
      context: .
    container_name: web
    restart: on-failure
    volumes:
      - ./:/usr/src/app
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PWD: ${MYSQL_PWD}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_EXPORT_PATH: ${MYSQL_EXPORT_PATH}
      SIDEKIQ_REDIS_HOST: ${SIDEKIQ_REDIS_HOST}
      SIDEKIQ_REDIS_PORT: ${SIDEKIQ_REDIS_PORT}
      SIDEKIQ_REDIS_DB: ${SIDEKIQ_REDIS_DB}
      SIDEKIQ_THREADS: 1
      SIDEKIQ_WEB_USER: ${SIDEKIQ_WEB_USER}
      SIDEKIQ_WEB_PASS: ${SIDEKIQ_WEB_PASS}
      RACK_SESSION_SECRET: ${RACK_SESSION_SECRET}
    command: './entrypoint.sh web'
    ports:
      - 3000:3000
    depends_on:
      - redis
    networks:
      - albiondata
    logging:
      options:
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
  sidekiq:
    image: ruby:3
    build:
      context: .
    container_name: sidekiq
    restart: on-failure
    volumes:
      - ./:/usr/src/app
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PWD: ${MYSQL_PWD}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_EXPORT_PATH: ${MYSQL_EXPORT_PATH}
      SIDEKIQ_REDIS_HOST: ${SIDEKIQ_REDIS_HOST}
      SIDEKIQ_REDIS_PORT: ${SIDEKIQ_REDIS_PORT}
      SIDEKIQ_REDIS_DB: ${SIDEKIQ_REDIS_DB}
      SIDEKIQ_THREADS: 1
      SIDEKIQ_WEB_USER: ${SIDEKIQ_WEB_USER}
      SIDEKIQ_WEB_PASS: ${SIDEKIQ_WEB_PASS}
    command: './entrypoint.sh sidekiq'
    depends_on:
      - redis
    networks:
      - albiondata
    logging:
      options:
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
  sleep:
    image: ruby:3
    build:
      context: .
    container_name: sleep
    restart: on-failure
    volumes:
      - ./:/usr/src/app
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PWD: ${MYSQL_PWD}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_EXPORT_PATH: ${MYSQL_EXPORT_PATH}
      SIDEKIQ_REDIS_HOST: ${SIDEKIQ_REDIS_HOST}
      SIDEKIQ_REDIS_PORT: ${SIDEKIQ_REDIS_PORT}
      SIDEKIQ_REDIS_DB: ${SIDEKIQ_REDIS_DB}
      SIDEKIQ_THREADS: 1
      SIDEKIQ_WEB_USER: ${SIDEKIQ_WEB_USER}
      SIDEKIQ_WEB_PASS: ${SIDEKIQ_WEB_PASS}
    command: './entrypoint.sh sleep'
    depends_on:
      - redis
    networks:
      - albiondata
    logging:
      options:
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
  redis:
    image: redis
    container_name: redis
    restart: on-failure
    ports:
      - 6379:6379
    volumes:
      - ./redisdata:/data
    command: redis-server --appendonly yes
    networks:
      - albiondata
networks:
  albiondata:
